import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavLink from "@/components/navLink ";
import LoginLink from "@/components/loginLink ";
import { NextAuthProvider } from "@/utils/providers ";
import { PetContextProvider } from "@/context/PetContext ";
import bg from "/public/scott-webb-UjupleczBOY-unsplash.jpg";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      className={inter.className}
      lang="en"
    >
      <body>
        <NextAuthProvider>
          <PetContextProvider>
            <header>
              <nav className="fixed top-0 w-full h-20 pl-10 flex items-center bg-transparent z-10">
                <div className="w-1/2">
                  <Link
                    href="/"
                    className="font-extrabold hover:font-bold text-2xl sm:text-3xl"
                  >
                    <span className="text-emerald-500 hover:text-emerald-600">
                      Lost
                    </span>
                    <span className="text-emerald-700 hover:text-emerald-800">
                      Pets
                    </span>
                  </Link>
                </div>
                <div className="flex justify-evenly items-center w-1/2 text-sm sm:text-lg text-emerald-600 font-bold">
                  <div className="hidden sm:block">
                    <NavLink href="/">Home</NavLink>
                  </div>
                  <NavLink href="/search">Search</NavLink>

                  <LoginLink />
                </div>
              </nav>
              <hr className="fixed top-20 left-10 right-10 border-b" />
            </header>
            <main className="relative w-screen h-screen">
              <Image
                src={bg}
                fill
                className="object-cover object-bottom"
                alt="Photo by Scott Webb at Unsplash"
              />
              {children}
            </main>
          </PetContextProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
